version: '2'
services:
  web:
    image: tutum/hello-world:latest
  nginx:
    build: .
    ports:
      - 8000:80
      - 8080:8080
    environment:
      - USERNAME=username
      - PASSWORD=password
      - PROXY_PASS=http://web/
